#!/bin/bash

NAME=chatbot-app
DIR=/home/devops/cs-chatbot/src
USER=devops
GROUP=devops
WORKERS=1
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=/home/devops/venvs/chatbot-v2/bin/activate
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=info
LOG_FILE=/home/devops/cs-chatbot/src/logs/gunicorn-output.log

cd $DIR
source $VENV

exec gunicorn main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=$LOG_FILE
